name: fire_book
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  cloud_firestore: ^3.1.8
  firebase_core: ^1.12.0
  firebase_auth: ^3.3.7
  flutter_bloc: ^8.0.1
  bloc: ^8.0.2
  http: ^0.13.4
  provider: ^6.0.2
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true